// <auto-generated />
namespace HoGameEIS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Storename : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Storename));
        
        string IMigrationMetadata.Id
        {
            get { return "201507140232020_Storename"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
